export const defaultCategories = [
  { id: "Groceries", name: "Groceries", iconUrl: "https://cdn.jsdelivr.net/npm/emoji-datasource-apple/img/apple/64/1f6d2.png" },
  { id: "Rent", name: "Rent", iconUrl: "https://cdn.jsdelivr.net/npm/emoji-datasource-apple/img/apple/64/1f3e0.png" },
  { id: "Utilities", name: "Utilities", iconUrl: "https://cdn.jsdelivr.net/npm/emoji-datasource-apple/img/apple/64/1f4a1.png" },
  { id: "Transportation", name: "Transportation", iconUrl: "https://cdn.jsdelivr.net/npm/emoji-datasource-apple/img/apple/64/1f697.png" },
  { id: "Food_and_Dining", name: "Food & Dining", iconUrl: "https://cdn.jsdelivr.net/npm/emoji-datasource-apple/img/apple/64/1f37d-fe0f.png" },
  { id: "Health_and_Fitness", name: "Health & Fitness", iconUrl: "https://cdn.jsdelivr.net/npm/emoji-datasource-apple/img/apple/64/1f4aa.png" },
  { id: "Shopping", name: "Shopping", iconUrl: "https://cdn.jsdelivr.net/npm/emoji-datasource-apple/img/apple/64/1f6cd-fe0f.png" },
  { id: "Entertainment", name: "Entertainment", iconUrl: "https://cdn.jsdelivr.net/npm/emoji-datasource-apple/img/apple/64/1f3ac.png" },
  { id: "Travel", name: "Travel", iconUrl: "https://cdn.jsdelivr.net/npm/emoji-datasource-apple/img/apple/64/2708-fe0f.png" },
  { id: "Education", name: "Education", iconUrl: "https://cdn.jsdelivr.net/npm/emoji-datasource-apple/img/apple/64/1f393.png" },
  { id: "Personal_Care", name: "Personal Care", iconUrl: "https://cdn.jsdelivr.net/npm/emoji-datasource-apple/img/apple/64/1f484.png" },
  { id: "Gifts_and_Donations", name: "Gifts & Donations", iconUrl: "https://cdn.jsdelivr.net/npm/emoji-datasource-apple/img/apple/64/1f381.png" },
  { id: "Investments", name: "Investments", iconUrl: "https://cdn.jsdelivr.net/npm/emoji-datasource-apple/img/apple/64/1f4b0.png" },
  { id: "Loans", name: "Loans", iconUrl: "https://cdn.jsdelivr.net/npm/emoji-datasource-apple/img/apple/64/1f4b3.png" },
  { id: "Taxes", name: "Taxes", iconUrl: "https://cdn.jsdelivr.net/npm/emoji-datasource-apple/img/apple/64/1f4c4.png" },
  { id: "Insurance", name: "Insurance", iconUrl: "https://cdn.jsdelivr.net/npm/emoji-datasource-apple/img/apple/64/1f512.png" },
  { id: "Pets", name: "Pets", iconUrl: "https://cdn.jsdelivr.net/npm/emoji-datasource-apple/img/apple/64/1f436.png" },
  { id: "Kids", name: "Kids", iconUrl: "https://cdn.jsdelivr.net/npm/emoji-datasource-apple/img/apple/64/1f476.png useEmojiModal.jsx:39:12" },
  { id: "Subscriptions", name: "Subscriptions", iconUrl: "https://cdn.jsdelivr.net/npm/emoji-datasource-apple/img/apple/64/1f4c6.png" },
  { id: "Others", name: "Others", iconUrl: "https://cdn.jsdelivr.net/npm/emoji-datasource-apple/img/apple/64/1f50d.png" },
];
