export const defaultCategories = [
  { id: "Groceries", name: "Groceries", icon: "🛒" },
  { id: "Rent", name: "Rent", icon: "🏠" },
  { id: "Utilities", name: "Utilities", icon: "💡" },
  { id: "Transportation", name: "Transportation", icon: "🚗" },
  { id: "Food_and_Dining", name: "Food & Dining", icon: "🍽️" },
  { id: "Health_and_Fitness", name: "Health & Fitness", icon: "💪" },
  { id: "Shopping", name: "Shopping", icon: "🛍️" },
  { id: "Entertainment", name: "Entertainment", icon: "🎬" },
  { id: "Travel", name: "Travel", icon: "✈️" },
  { id: "Education", name: "Education", icon: "🎓" },
  { id: "Personal_Care", name: "Personal Care", icon: "💄" },
  { id: "Gifts_and_Donations", name: "Gifts & Donations", icon: "🎁" },
  { id: "Investments", name: "Investments", icon: "💰" },
  { id: "Loans", name: "Loans", icon: "💳" },
  { id: "Taxes", name: "Taxes", icon: "📄" },
  { id: "Insurance", name: "Insurance", icon: "🔒" },
  { id: "Pets", name: "Pets", icon: "🐶" },
  { id: "Kids", name: "Kids", icon: "👶" },
  { id: "Subscriptions", name: "Subscriptions", icon: "📆" },
  { id: "Others", name: "Others", icon: "🔍" },
];
